// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/assets/[name].tsx";
import * as $2 from "./routes/assets/api/joke.ts";
import * as $3 from "./routes/blog.tsx";
import * as $4 from "./routes/contact.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/info.tsx";
import * as $7 from "./routes/posts/[id].tsx";
import * as $8 from "./routes/server/apis/GetTweetAPI.ts";
import * as $9 from "./routes/tool/index.tsx";
import * as $10 from "./routes/tool/report/index.tsx";
import * as $11 from "./routes/tool/tashiro/atk/[name].tsx";
import * as $12 from "./routes/tool/tashiro/index.tsx";
import * as $13 from "./routes/tools.tsx";
import * as $14 from "./routes/works.tsx";
import * as $$0 from "./islands/Links.tsx";
import * as $$1 from "./islands/Skills.tsx";
import * as $$2 from "./islands/Tools.tsx";
import * as $$3 from "./islands/Works.tsx";
import * as $$4 from "./islands/blog/BlogList.tsx";
import * as $$5 from "./islands/client/atk.tsx";
import * as $$6 from "./islands/client/report.tsx";
import * as $$7 from "./islands/client/visit.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/assets/[name].tsx": $1,
    "./routes/assets/api/joke.ts": $2,
    "./routes/blog.tsx": $3,
    "./routes/contact.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/info.tsx": $6,
    "./routes/posts/[id].tsx": $7,
    "./routes/server/apis/GetTweetAPI.ts": $8,
    "./routes/tool/index.tsx": $9,
    "./routes/tool/report/index.tsx": $10,
    "./routes/tool/tashiro/atk/[name].tsx": $11,
    "./routes/tool/tashiro/index.tsx": $12,
    "./routes/tools.tsx": $13,
    "./routes/works.tsx": $14,
  },
  islands: {
    "./islands/Links.tsx": $$0,
    "./islands/Skills.tsx": $$1,
    "./islands/Tools.tsx": $$2,
    "./islands/Works.tsx": $$3,
    "./islands/blog/BlogList.tsx": $$4,
    "./islands/client/atk.tsx": $$5,
    "./islands/client/report.tsx": $$6,
    "./islands/client/visit.tsx": $$7,
  },
  baseUrl: import.meta.url,
};

export default manifest;
